### ISSUE TITLE
Wahoo VS Oh My Fish! 

### ISSUE THREAD

**Issue by jrobeson** [wa/wahoo#95] opened 2015-08-27 02:27 UTC
I still have no idea what happened and why the merge was aborted. Until I know that, I'd have some problems moving to a new project.

**Comment by bucaran** [comment] 2015-08-27 05:20
Ah, good point. Will do shortly.

**Comment by bucaran** [comment] 2015-09-06 08:15
![wahoo](https://cloud.githubusercontent.com/assets/8317250/9703317/d216df50-54ba-11e5-81b9-8cc92fa3f76a.png)

**Comment by bucaran** [comment] 2015-09-06 08:16
I am working on a new system and set of tools to supersede Wahoo, OMF, etc. It will be hosted inside the new org, [Fishline](https://github.com/fishline).

**Comment by jrobeson** [comment] 2015-09-06 08:26
I still have no idea what happened and why the merge was aborted. Until I know that, I'd have some problems moving to a new project.

**Comment by bucaran** [comment] 2015-09-06 08:37
Short summary:

* OMF upgraded to Wahoo. Code base was completely replaced with current Wahoo.
* OMF underwent several minor improvements, help system was improved a lot.
* The first Fish wars took place with irreparable damage.
* OMF continues the Wahoo lineage with plans to improve it and support previous incarnations of Oh My Fish!
* I am working (for release in a few days) on a new framework, [Fin](https://github.com/fishline/fin/), my best iteration so far, not just another rewrite, but a completely different internal architecture and system.

![fin](https://cloud.githubusercontent.com/assets/8317250/9703391/dadfeb4c-54bd-11e5-8f52-aa19d8de48f3.png)

**Comment by jrobeson** [comment] 2015-09-06 08:44
I'm interested in knowing what these disagreements entail so that I can choose which project I want to follow along with

**Comment by bucaran** [comment] 2015-09-06 09:42
To make a long story short, here is what happened, minus the editorialization:

I worked in OMF for almost a year. During this time I was the most prolific contributor and still have the most additions to the project to this day. I also shared the admin rights. Right which was given to me by Bruno after working together for a few months.

Eventually for some of the reasons given above, I rolled my own Wahoo. During this time I was still an owner at Oh My Fish! and helped with issues and support. After a while we decided to merge after Bruno finally admitted Wahoo was superior. We then moved the repository to the `fish-shell` organization as a "status symbol" perhaps? We did this by *mutual agreement*.

We still had some minor disagreements, like how to handle automatic updates, which components should be more modular, backwards compatibility, etc, but things went awry when I created an issue asking the community "What if Oh My Fish! had a different name?". Two people were against the idea so Bruno closed the issue. 

I felt this was too quick and wanted to hear other opinions so I reopened it. He then closed it again and unilaterally decided to transfer the repo from `fish-shell` back to `oh-my-fish` in a move I was not expecting and presumably with the intention to take me off the admin group (repo owners can add other owners as well as remove them).

He could have let me know first in the Gitter channel or send me a private message, but he acted without my participation, so I quickly reacted by moving the repository from `oh-my-fish` to `wa` as a temporary measure.

In the end we could not reach an agreement and they asked me to take down the repo, or they would submit a DMCA clause and other nonsense. I did.

Not happy with the outcome I regret it this move and asked GitHub to restore the repo. They did.

**Comment by gretel** [comment] 2015-09-18 15:35
`DMCA`, really? wtf.

**Comment by derekstavis** [comment] 2015-09-18 20:40
Wahoo merge was unresponsible from stability point of view, and you managed to force push master branch two times in a row, completely violating the history, even when everyone was trying hard to go through pull requests and discussing before merging anything. Backwards compatibility wasn't taken account in the merge. It was a project managers fault, not just yours.

I, as a simple user at that time, went crazy with `omf` breaking in all machines I had it, so I tried help cover the holes that the merge left behind, like having a declarative file with installed plugins/themes and some kind of backwards compatibility, as soon as possible, as a strategy to affect a minimum amount of users. Then you dominated the matter and came with a very complex pull request which was difficult to review and changed things out of its scope. As the solution wasn't clear to merge I've done my best to offer a better pull request which went through review and lagged behind because you, as a core developer, didn't want to comment on the matter.

**Comment by jrobeson** [comment] 2015-09-18 20:59
@derekstavis : agreed. I'm not sure where to go for my fish framework needs atm. I like where @bucaran is going with his code for fishline, but I wouldn't want to see something like that happen again, Nor am I happy to see a DMCA request filed from oh my fish.

**Comment by jrobeson** [comment] 2015-09-18 21:00
I think there's a huge communication problem here, that I don't know how to solve.

**Comment by derekstavis** [comment] 2015-09-18 21:05
I think we are done with issues. Indeed there was a huge communication problem and it was decided to split the projects. In a way or other the best project will stand, and thus the community will benefit from it.

**Comment by jrobeson** [comment] 2015-09-18 21:21
I disagree about the community benefiting from it. I wouldn't benefit as a developer if there were multiple competitors to pip (in python), bundler (in ruby), composer (in php)

**Comment by bucaran** [comment] 2015-09-18 23:33
The merge was a bad move, it should have been coordinated via a separate branch with an agreement regarding ownership and copyright. 

OMF is just Wahoo, with a different name and with my name conspicuously missing from their LICENSE.

In concrete, new in OMF is a nicer help and the _bundle_ concept which is the best new idea. Other than that is just small stuff.

Fin, which I should release sooner than later, is a complete rewrite and a more mature project.

>  I wouldn't want to see something like that happen again

Me neither.

**Comment by gretel** [comment] 2015-09-19 14:56
@derekstavis the best project will stand? split the projects? benefit from it? may i suggest you checking on the reality you are perceiving? regards

**Comment by bucaran** [comment] 2015-09-19 15:21
Some history trivia, I created Wahoo because @bpinto and I had different views on how to manage the original OMF (more trivia: to this date I am still the committer with more contributions `6,696 ++ / 4,032 --` to oh my fish).

**Comment by derekstavis** [comment] 2015-09-19 15:22
Yes @gretel, at least for the time being it's the best thing to do. Benefitting from split projects can be seen as what happened with nodejs/iojs, which the main project stand with more conservative views, while the fork started experimenting with new functionalities and core changes, without trying to force merge stuff into the main project. Eventually nodejs saw that iojs was great and agreed on merging the projects. Benefit to the community, as users didn't had to be affected by iojs bleeding changes.

**Comment by derekstavis** [comment] 2015-09-19 15:26
When people can't agree on a specific solution and there's a contributor or set of contributors which thinks that owns the project the best thing to do is to fork. We have seen this a lot in the open source world and I saw lots of benefits from fork/merge concept.

**Comment by gretel** [comment] 2015-09-19 15:30
@derekstavis ripping off code and pretend it's a good thing to do so? i dont think you are in a position to decide what might be best, because i don't see what you  have done for the project. considering this discussion maybe i should file a DMCA, because i don't find my name in relation to the copyright neither.

**Comment by bucaran** [comment] 2015-09-19 15:42
> When people can't agree on a specific solution and there's a contributor or set of contributors which thinks that owns the project the best thing to do is to fork.

We should have first used either Wahoo or a dev branch to get to a point we were all happy before the merge.

**Comment by derekstavis** [comment] 2015-09-19 15:46
First: I haven't decided anything, I just exposed my thoughts on open source software, which isn't applicable only to this issue.
Second: All this problems could be solved easily if Jorge gave back the original repository, which was a property of Bruno. We all know that this theft was done because of project stars. It's pretty strange that Fin with no code have 800+ stars.

**Comment by bucaran** [comment] 2015-09-19 15:53
> All this problems could be solved easily if Jorge gave back the original repository, which was a property of Bruno. 

It was mine too, we shared copyright, it was a mutual organization.

**Comment by bucaran** [comment] 2015-09-19 16:08
@derekstavis 
> All this problems could be solved easily if Jorge gave back the original repository, which was a property of Bruno. 

This is false. We _shared_ copyright as it was a **mutual organization**. While Bruno did create the original repo, I wrote most of the code, and when we transferred to an organization I became an administrator. 

Giving the repo back was giving up on everything, because we all know [who actually owns](https://github.com/oh-my-fish/oh-my-fish/commit/bf90837007dd1ea274267ff4f05e05ad8717ac09) Oh My Fish! and what he was planning to do.

Why don't you folks revert the merge and go back to pre-Wahoo?

**Comment by bucaran** [comment] 2015-09-19 16:08
@derekstavis / cc  @bpinto
> All this problems could be solved easily if Jorge gave back the original repository, which was a property of Bruno. 

This is false. We _shared_ copyright as it was a **mutual organization**. While Bruno did create the original repo, I wrote most of the code, and when we transferred to an organization I became an administrator. 

Giving the repo back was giving up on everything, because we all know [who actually owns](https://github.com/oh-my-fish/oh-my-fish/commit/bf90837007dd1ea274267ff4f05e05ad8717ac09) Oh My Fish! and what he was planning to do.

Why don't you folks revert the merge and go back to pre-Wahoo?

**Comment by derekstavis** [comment] 2015-09-19 16:21
Fair @bucaran. Linking to contributors page on repo looks good to you?

**Comment by bucaran** [comment] 2015-09-19 16:26
OMF is essentially Wahoo sans the name. Since I am no longer an owner in the project, I think it does not make sense to keep basing OMF in Wahoo.

**Comment by bucaran** [comment] 2015-09-19 16:26
@derekstavis 

> All this problems could be solved easily if Jorge gave back the original repository, which was a property of Bruno. 

This is false. We _shared_ copyright as it was a **mutual organization**. While Bruno did create the original repo, I wrote most of the code, and when we transferred to an organization I became an administrator. 

Giving the repo back was giving up on everything, because we all know [who actually owns](https://github.com/oh-my-fish/oh-my-fish/commit/bf90837007dd1ea274267ff4f05e05ad8717ac09) Oh My Fish! and what he was planning to do.

/ cc 
@bpinto
@bobthecow
@bucaran
@rominf
@derekstavis
@tannhuber
@jhillyerd
@scorphus
@skk
@krisleech
@jacaetevha
@tripleplus
@felipero
@jeremiejig
@vincent-psarga
@farao
@ngroup
@sheldon
@syl20bnr
@joar
@amio
@jacobono
@theonewolf
@xorgy
@lvicentesanchez
@godfat
@kiRach
@jonknapp
@beloglazov
@cap10morgan
@tanob
@iven
@daveyarwood
@numist
@charlesbjohnson
@RobDay
@wzhishen
@sn0cr
@JBarberU
@taktoa
@wk
@Paulloz
@rahult
@exdis
@JeanMertz
@idan
@CodeFalling
@Bastes
@uggedal
@ramitos
@peteretep
@ohspite
@nirvdrum
@liquid
@dgarrett
@natrim
@Lavoaster
@jonathanpa
@erikkallen
@zhuangya
@CyberShadow
@osamu2001
@vincentjames501
@williamhogman
@dan-c-underwood
@janlindblom
@exzz
@CADBOT
@greggles
@steeeve
@ilkosta
@michelegera
@oneKelvinSmith
@nesl247
@joshuawarner32
@jcouyang
@celsomiranda
@daenney
@unbalancedparentheses
@kholbekj
@bbbenji
@adevore
@ccwang002
@inxilpro
@Fryie
@froztbyte
@despairblue
@Mic92
@fibric
@zdavison
@KnightHawk3
@phaedryx
@aznashwan
@andyklimczak
@mtahmed
@josiahsprague
@hsharrison
@talios
@lloydde
@andrelfpinto

**Comment by bucaran** [comment] 2015-09-19 16:27
/cc

@peteretep
@ohspite
@nirvdrum
@liquid
@dgarrett
@natrim
@Lavoaster
@jonathanpa
@erikkallen
@zhuangya
@CyberShadow
@osamu2001
@vincentjames501
@williamhogman
@dan-c-underwood
@janlindblom
@exzz
@CADBOT
@greggles
@steeeve
@ilkosta
@michelegera
@oneKelvinSmith
@nesl247
@joshuawarner32
@jcouyang
@celsomiranda
@daenney
@unbalancedparentheses
@kholbekj
@bbbenji
@adevore
@ccwang002
@inxilpro
@Fryie
@froztbyte
@despairblue
@Mic92
@fibric
@zdavison
@KnightHawk3
@phaedryx
@aznashwan
@andyklimczak
@mtahmed
@josiahsprague
@hsharrison
@talios
@lloydde
@andrelfpinto

**Comment by bucaran** [comment] 2015-09-19 16:30
OMF is essentially Wahoo sans the name. Since I am no longer an owner in the project, I think it does not make sense to keep basing OMF in Wahoo. I mean, what's wrong with the older OMF anyway?

**Comment by bucaran** [comment] 2015-09-19 16:33
> Linking to contributors page on repo looks good to you?

That would be misleading, because the contributors page shows OMF history before it was entirely replaced with Wahoo. Mmm.

**Comment by derekstavis** [comment] 2015-09-19 16:43
I'm not inclined to go back. You wanted to merge Wahoo into it, so it was done. Now we are working to fix the regressions and make OMF great for everyone again.

Also, I see no problems acknowledging that current OMF code is greater than current Wahoo, which is **far** greather than older OMF, even with its issues.

But yes, the right thing to be done is to give credits to everyone who contributed, and state that current OMF is based on Wahoo, as no one wants to take credit on code from anyone.

**Comment by derekstavis** [comment] 2015-09-19 16:48
>That would be misleading, because the contributors page shows OMF history before it was entirely replaced with Wahoo. Mmm.

Theres no licensing issues with this as long as we reference your work.

**Comment by bobthecow** [comment] 2015-09-19 16:50
@bucaran You stole a repo from _me_ and @bpinto. You gutted it, closed all the issues, and removed it from the GitHub fork tree.

We were also owners and contributors. You are completely in the wrong here. I have no interest in interacting with you on open source projects in the future, because I do not trust you. You are volatile and toxic to this community.

I would have been happy to discuss my feelings in private, but you have just turned it into a public conversation.

**Comment by bobthecow** [comment] 2015-09-19 16:53
You are completely in the wrong here.

You stole a repo from @bpinto and me. We were also owners and contributors. We were both involved in it longer than you. @bpinto started it, for crying out loud. You took advantage of his trust in you to hijack hundreds of stars and watchers, most of which predated your involvement in the project, and nearly all of which predated the Wahoo merge.

After you hijacked this community’s repository, you took the repo on a high speed chase through your personal account and multiple organizations. You turned it from private to public, changed its name multiple times, then made it public again. You gutted it, closed all the pull requests and issues. You deleted issues and comments critical of your actions. You removed the repo from the GitHub fork tree, so now it looks like a standalone project. You rejected countless attempts to resolve this amicably, by your fellow owners as well as concerned contributors and community members alike.

You are volatile and toxic to this community.

I have no interest in interacting with you on open source projects in the future, because I do not trust you.

/cc @rominf @tannhuber @jhillyerd @scorphus @skk @krisleech @jacaetevha @tripleplus @felipero @jeremiejig @vincent-psarga @farao @ngroup @sheldon @syl20bnr @joar @amio @jacobono @theonewolf @xorgy @lvicentesanchez @godfat @kiRach @jonknapp @beloglazov @cap10morgan @tanob @iven @daveyarwood @numist @charlesbjohnson @RobDay @wzhishen @sn0cr @JBarberU @taktoa @wk @Paulloz @rahult @exdis @JeanMertz @idan @CodeFalling @Bastes @uggedal @ramitos @peteretep @ohspite @nirvdrum @liquid @dgarrett @natrim @Lavoaster @jonathanpa @erikkallen @zhuangya @CyberShadow @osamu2001 @vincentjames501 @williamhogman @dan-c-underwood @janlindblom @exzz @CADBOT @greggles @steeeve @ilkosta @michelegera @oneKelvinSmith @nesl247 @joshuawarner32 @jcouyang @celsomiranda @daenney @unbalancedparentheses @kholbekj @bbbenji @adevore @ccwang002 @inxilpro @Fryie @froztbyte @despairblue @Mic92 @fibric @zdavison @KnightHawk3 @phaedryx @aznashwan @andyklimczak @mtahmed @josiahsprague @hsharrison @talios @lloydde @andrelfpinto

**Comment by bucaran** [comment] 2015-09-19 16:53
@bobthecow 
> @bucaran You stole a repo from me and @bpinto. You gutted it, closed all the issues, and removed it from the GitHub fork tree.

This is false. We shared copyright as it was a mutual organization. While Bruno did create the original repo, I wrote most of the code, and when we transferred to an organization I became an administrator.

Indeed, you were also an admin. But you are clearly sided with @bpinto so I had no choice to act as I did. This has been addressed before multiple times.

**Comment by bobthecow** [comment] 2015-09-19 16:54
> Indeed, you were also an admin. But you are clearly sided with @bpinto so I had no choice to act as I did. This has been addressed before multiple times.

You did have a choice. You made the wrong one.

**Comment by bucaran** [comment] 2015-09-19 16:57
[What happened is clearly described here without any editorialization.](https://github.com/wa/wahoo/issues/95#issuecomment-138061127)

I reacted. Actually, FYI, I **deleted** the repo after a long conversation with @bpinto and @derekstavis over gitter. Then, I pushed the pre-wahoo OMF to the organization [here](https://github.com/oh-my-fish/framework), which is what I thought Bruno was looking for. Then I was removed from the org.

I was able to get the repo restored

**Comment by bucaran** [comment] 2015-09-19 17:07
> You deleted issues and comments critical of your actions.

No issues have been mutilated or edited. I have just temporarily closed the issue tracker while I work on Fin. But I have reopened them again.

**Comment by bobthecow** [comment] 2015-09-19 17:08
> No issues have been mutilated or edited.

I watched you rename an issue that was critical of your actions, and delete all its comments one by one.

**Comment by bobthecow** [comment] 2015-09-19 17:08
Oh, here it is: https://github.com/fishline/fin/issues/593

Look, the change history shows the original issue title. Huh.

**Comment by bobthecow** [comment] 2015-09-19 17:10
(preserved for posterity, in case you decide to disable issues again)

<img width="1044" alt="" src="https://cloud.githubusercontent.com/assets/53660/9977301/9723e428-5eb6-11e5-9d83-cc05d57ac73e.png">

**Comment by bucaran** [comment] 2015-09-19 17:10
Right. The content is essentially the same as https://github.com/fishline/fin/issues/594 and https://github.com/fishline/fin/issues/595. I don't remember what I was planning to do at the time. It probably seemed like a lot of work to edit issues, so I left everything as is. The discussion there is essentially the contents of this thread.

**Comment by bobthecow** [comment] 2015-09-19 17:10
You just lied to me.

**Comment by bobthecow** [comment] 2015-09-19 17:10
Literally, your last comment was a lie.

**Comment by bucaran** [comment] 2015-09-19 17:13
You are literally manipulating this conversation. I did edit that one issue as it was not clear what would happen at that point. I didn't want these three dudes to keep littering all over the repo. The contents of that thread is essentially the discussion here, but in a much less organized fashion.

**Comment by bobthecow** [comment] 2015-09-19 17:17
The contents of that thread is gone, so you can say it was about whatever you want, right?

I maintain my position that your actions are volatile and not worthy of my trust. You're not saying or doing anything to convince me otherwise, you're just digging in deeper.

**Comment by bobthecow** [comment] 2015-09-19 17:20
And now you're changing the conversation here as I point out your further lies. Don't worry, this time there's an email record ;)

**Comment by bucaran** [comment] 2015-09-19 17:20
> The contents of that thread is gone, so you can say it was about whatever you want, right?

I am sorry the contents is gone, that would certainly bring an end to this conspiracy theory exchange.

**Comment by Fryie** [comment] 2015-09-19 17:23
What is this nonsense. I have no desire to become involved in some political squabble here. Please stop tagging everyone @bucaran

**Comment by bucaran** [comment] 2015-09-19 17:24
@Fryie Feel free to untag you from the /cc.

**Comment by bobthecow** [comment] 2015-09-19 17:32
> … but claiming that there was something crucial to whatever happened here is ridiculous. The contents is basically me discussing with Derek why I moved OMF to the Wahoo org, essentially this discussion.

It's support for my claims. You deleted comments and issues critical of your actions, then denied it, then deleted your denial after I provided proof. It's just one more reason I don't trust you.

**Comment by bucaran** [comment] 2015-09-19 17:36
Please consider any of the following:

+ Revert back to pre-Wahoo. If this is not desirable please express the reasons.
+ Use a different name and update copyright notice / add notice in README.
+ Continue development over in Wahoo. I will add the interested parties to the owner group at your request.

**Comment by derekstavis** [comment] 2015-09-19 17:49
I will stop commenting here as you are  moderating hard this issue by deleting comments.

**Comment by rominf** [comment] 2015-09-19 17:53
Hi everyone! I've added my 50 cents to oh-my-fish, so I feel a little bit interested about this conversation.

First of all, I saw `wa/wahoo` repository only today.

Here is my point of view. Bruno started this project long time ago, he maintained it. @bucaran states that he made a full rewrite of `on-my-fish`. OK, at first blush (by github's contribution page) it appears to be true, BUT still an initial author of `oh-my-fish` and repository owner is @bpinto, so it's he's responsibility to decide what to do with the code. If @bucaran contributed to a project — great! But he submitted this code into the `oh-my-fish`, so he knew, that this code will be under @bpinto jurisdiction. Sure, @bucaran can fork `oh-my-fish` and continue developing it, but he cannot force @bpinto rename/delete/etc. `oh-my-fish` repository. That's my opinion.

**Comment by bucaran** [comment] 2015-09-19 17:57
@rominf

Under normal circumstances you would be correct, but we actually _shared_ copyright over the project as it was a mutual organization. Let me clarify, while Bruno did create the original repo, I wrote most of it at some point, and when we transferred to an organization I became an administrator along with @bobthecow.

I am asking to rename because OMF no longer exists, and it's basically Wahoo with a different name, but without fair copyright. If they think it was wrong to merge, they should revert to the pre-Wahoo Oh My Fish! and continue developing.

**Comment by derekstavis** [comment] 2015-09-19 17:59
I hope you stop removing comments that don't favor your opinion from this issue and also let people share his own views without your interference.

**Comment by rominf** [comment] 2015-09-19 18:09
@bucaran 
I get your point. I understand you. I'm not a lawyer, but as I understand this situation, @bpinto has property rights for `oh-my-fish`, and you have author's rights for your code (all commit's you've done, even if `oh-my-fish` 100% consisted of your commits) and property rights for `wa/wahoo`.

**Comment by bucaran** [comment] 2015-09-19 18:12
@rominf Yeah. Asking to rename is a waste of time.

**Comment by bobthecow** [comment] 2015-09-19 18:13
> @bobthecow ← @derekstavis ← Please keep the conversation to the point if you want to participate.

@bucaran I responded to your statements after _you_ included _me_ in this conversation about "WTF happened to OMF." _You_ are the one derailing the conversation and deleting everyone's comments.

**Comment by rominf** [comment] 2015-09-19 18:25
I think that those two projects can coexist, and no one owes nothing to nobody.

@bucaran 
You have submitted your code to `oh-my-fish` repository. What's done that's done. You can kindly ask for removing your code and rewriting everything from scratch, but you cannot force @bpinto, it's @bpinto's decision after all.

> if they don't need me in the project, they certainly don't need my code
I don't agree with you. You are not your code. Those two concepts are distinct. Your code is worthwhile, you just made a mistake (if you are not satisfied now) by putting it into `oh-my-fish` repository. I can imagine me in your place, I would be disappointed too.

**Comment by bucaran** [comment] 2015-09-19 18:30
> You have submitted your code to oh-my-fish repository. What's done that's done. You can kindly ask for removing your code and rewriting everything from scratch, but you cannot force @bpinto, it's @bpinto's decision after all.

You are right, I can't force anyone do anything :smile:

**Comment by rominf** [comment] 2015-09-19 18:49
@bucaran 
I think that the best approach is to get rid of those copyrights in code and just write "project owner is ..., to see code authors see git commits authors, output of `git blame` command or GitHub's Graphs page". And it can be clearly seen how much does anyone contributed to the project.

**Comment by bpinto** [comment] 2015-09-19 19:21
It's so sad to see a discussion regarding code ownership in a open source project.

@bucaran look at the old omf code and wahoo, including plugins. They are a shameless copy and paste. The code since the merge has changed considerably as Wahoo was buggy. Most files have already been touched with amazing improvements.

I don't think wahoos code was better, I wish I hadn't merged, this is the main reason why we are working hard towards getting the framework to behave the way it used to.

Honestly, all you care about is the fame. You don't care about the community, that's the simplest truth. I have naively given you owner rights in the repository as I thought you were valuable to the project, I couldn't be more wrong.

I will ignore this issue from now on as I know you don't want to talk about anything here, you just want people to know about fin or however you call it. You don't fool me no more.

It's easy to have LOC changed or number of commits in a repository, what is hard is to keep a community for over three years without making any penny out of it. How many hours have I spent working on plugins I don't use and features others needed? What about everyone else that has contributed? And you stole a project, delete its code base, its issues... What do you expect from us? Respect?

Do whatever you want, but stop crying. Cause we will never respect you again.

@rominf the license file on all plugins were added in a batch, feel free to modify it. When I started omf it didn't even had a license file, because I couldn't care less about it. But people alerted me that I should and we as a team (bucaran was not even on board IIRC) added it.

The main omf license file was always under my name, it was wrongly modified in the merge, contributors were not even aware of this change, so it was not legitimate.

**Comment by bucaran** [comment] 2015-09-19 19:34
This thread is locked. 

Wahoo users continue to enjoy Wahoo. 
Oh My Fish! users continue to enjoy Wahoo.

@bpinto I wanted to come to an agreement, but I can't continue this discussion.

**Comment by bobthecow** [comment] 2015-09-19 22:45
If you were right, you wouldn't have to delete everyone's comments telling you you're wrong. 

I'm done with this thread too, because you'll just delete what I say anyway ;)

If you want to have a fair conversation, let's hold it somewhere you don't have admin access.

**Comment by jrobeson** [comment] 2015-09-20 01:47
If you didn't know what you were doing (when moving repositories,renaming, etc) then you should have asked. I think you owe the community an apology

**Comment by bucaran** [comment] 2015-09-20 01:52
I acted correctly as described here → https://github.com/wa/wahoo/issues/95#issuecomment-138061127

I think Bruno and company owe me one, but I am not even remotely looking for one :smile:

**Comment by jrobeson** [comment] 2015-09-20 01:59
There seems to be some disagreement about that. Otherwise this thread wouldn't be existing?

**Comment by bucaran** [comment] 2015-09-20 01:59
Why did you conclude that I am the one who erred?

**Comment by jrobeson** [comment] 2015-09-20 02:03
who else would be deleting comments?

**Comment by jrobeson** [comment] 2015-09-20 02:03
All i wanted was a fish plugin manager that respected XDG.. that's it. I didn't expect to walk into this mess that is going on.

**Comment by bucaran** [comment] 2015-09-20 02:05
> who else would be deleting comments?

What do comments that attack me have to do with the topic of this thread? :smile:

**Comment by jrobeson** [comment] 2015-09-20 02:34
I might be able to understand deleting comments from folks who aren't really involved in development and are just sniping you, but I don't think you should be deleting comments from folks closely involved with oh-my-fish like @bobthecow

**Comment by bucaran** [comment] 2015-09-20 02:42
? He is giving a much opinionated account of the situation, saying things like I _stole_, and what not, which is just completely false and I had enough.

**Comment by jrobeson** [comment] 2015-09-20 02:45
but what is his motivation to lie?

**Comment by bucaran** [comment] 2015-09-20 02:50
He is cautious and took the safer side back to normal with Bruno. He probably believes Bruno is the only owner in OMF despite the fact I _was_ also an admin / owner and had written most of the code for it.

He probably ignores the fact Bruno moved the repo back to OMF without my participation. He also probably dislikes the fact I was reckless and before getting kicked out (which was Bruno's motivation to transfer the repo back to OMF and make me a collaborator just because I created an issue asking to consider changing the name of the framework as a ***thought experiment***) from my own project, I reacted and moved the original repo to an organization in which they didn't have control over.

**Comment by kholbekj** [comment] 2015-09-20 10:03
@jrobeson You can probably assume @bucaran is in wrong here. If nothing else, then solely based on the censorship, which is going on on everything that doesn't support his opinion.
Also, his talking about ownership, what is fair to him, and whatnot in an OS discussion, where all the others are talking about best for community.

**Comment by sheldon** [comment] 2015-09-20 13:27
> > who else would be deleting comments?

> Comments attacking me? Yes. I will delete those.

Asserting your admin rights over a discussion thread by deleting posts is a pretty juvenile way to counter a post attacking you.

If it's genuinely an attack and not valid that can be made obvious by good counter discussion.

Deleting posts only makes you seem guilty of what you're being accused of dude.

**Comment by bucaran** [comment] 2015-09-24 18:10
<h1>:point_right:  <a href="https://news.ycombinator.com/item?id=10271304">news.ycombinator.com/item?id=10271304....</a></h1>

**Comment by bucaran** [comment] 2015-09-24 18:11
@bpinto @bobthecow @bucaran @rominf @derekstavis @tannhuber @jhillyerd @scorphus @skk @krisleech @jacaetevha @tripleplus @felipero @jeremiejig @vincent-psarga @farao @ngroup @sheldon @syl20bnr @joar @amio @jacobono @theonewolf @xorgy @lvicentesanchez @godfat @kiRach @jonknapp @beloglazov @cap10morgan @tanob @iven @daveyarwood @numist @charlesbjohnson @RobDay @wzhishen @sn0cr @JBarberU @taktoa @wk @Paulloz @rahult @exdis @JeanMertz @idan @CodeFalling @Bastes @uggedal @ramitos @peteretep @ohspite @nirvdrum @liquid @dgarrett @natrim @Lavoaster @jonathanpa @erikkallen @zhuangya @CyberShadow @osamu2001 @vincentjames501 @williamhogman @dan-c-underwood @janlindblom @exzz @CADBOT @greggles @steeeve @ilkosta @michelegera @oneKelvinSmith @nesl247 @joshuawarner32 @jcouyang @celsomiranda @daenney @unbalancedparentheses @kholbekj @bbbenji @adevore @ccwang002 @inxilpro @Fryie @froztbyte @despairblue @Mic92 @fibric @zdavison @KnightHawk3 @phaedryx @aznashwan @andyklimczak @mtahmed @josiahsprague @hsharrison @talios @lloydde @andrelfpinto

**Comment by bucaran** [comment] 2015-09-24 18:11
@Lavoaster @jonathanpa @erikkallen @zhuangya @CyberShadow @osamu2001 @vincentjames501 @williamhogman @dan-c-underwood @janlindblom @exzz @CADBOT @greggles @steeeve @ilkosta @michelegera @oneKelvinSmith @nesl247 @joshuawarner32 @jcouyang @celsomiranda @daenney @unbalancedparentheses @kholbekj @bbbenji @adevore @ccwang002 @inxilpro @Fryie @froztbyte @despairblue @Mic92 @fibric @zdavison @KnightHawk3 @phaedryx @aznashwan @andyklimczak @mtahmed @josiahsprague @hsharrison @talios @lloydde @andrelfpinto

**Comment by bucaran** [comment] 2015-09-24 18:11
v @cap10morgan @tanob @iven @daveyarwood @numist @charlesbjohnson @RobDay @wzhishen @sn0cr @JBarberU @taktoa @wk @Paulloz @rahult @exdis @JeanMertz @idan @CodeFalling @Bastes @uggedal @ramitos @peteretep @ohspite @nirvdrum @liquid @dgarrett @natrim

**Comment by bucaran** [comment] 2015-09-24 18:11
<h3>:point_right:  <a href="https://news.ycombinator.com/item?id=10271304">news.ycombinator.com/item?id=10271304....</a></h3>

**Closed** 2015-09-26 23:22 UTC
Labels: docs, question
